# Cloudflare Workers configuration for BrainSAIT Healthcare SDK Worker
name = "brainsait-healthcare-sdk-worker"
main = "./dist/worker/index.js"
compatibility_date = "2023-10-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

# Environment variables
[vars]
ENVIRONMENT = "production"
SDK_VERSION = "1.2.0"
FHIR_BASE_URL = "https://fhir.nphies.sa"
NPHIES_BASE_URL = "https://nphies.sa"
LOG_LEVEL = "info"
MONGODB_ATLAS_URI = "mongodb+srv://fadil_db_user:1rlK8vj6YF5reQoc@cluster0.ozzjwto.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
DATABASE_NAME = "brainsait_platform"

# Development environment
[env.development]
name = "brainsait-healthcare-sdk-worker-dev"
workers_dev = true

[env.development.vars]
ENVIRONMENT = "development"
SDK_VERSION = "1.2.0"
FHIR_BASE_URL = "https://fhir-sandbox.nphies.sa"
NPHIES_BASE_URL = "https://nphies-sandbox.sa"
LOG_LEVEL = "debug"
MONGODB_ATLAS_URI = "mongodb+srv://fadil_db_user:1rlK8vj6YF5reQoc@cluster0.ozzjwto.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
DATABASE_NAME = "brainsait_platform_dev"

# Limits and optimization
limits = { cpu_ms = 50000 }
placement = { mode = "smart" }

# Analytics and observability
observability = { enabled = true }
logpush = true